export * from "./adrena";
export * from "./alldomains";
export * from "./dexscreener";
export * from "./alldomains";
export * from "./flash";
export * from "./gibwork";
export * from "./jupiter";
export * from "./lulo";
export * from "./manifest";
export * from "./solana";
export * from "./agent";
export * from "./metaplex";
export * from "./openbook";
export * from "./orca";
export * from "./pumpfun";
export * from "./pyth";
export * from "./raydium";
export * from "./rugcheck";
export * from "./sendarcade";
export * from "./solayer";
export * from "./tensor";
export * from "./3land";
export * from "./tiplink";
export * from "./sns";
export * from "./lightprotocol";
export * from "./squads";
export * from "./meteora";
export * from "./helius";
export * from "./drift";
export * from "./voltr";
export * from "./mayan";
export * from "./allora";
export * from "./solutiofi";
export * from "./switchboard";
export * from "./elfa_ai";
export * from "./debridge";
export * from "./fluxbeam";

import type { SolanaAgentKit } from "../agent";
import {
  SolanaBalanceTool,
  SolanaBalanceOtherTool,
  SolanaTransferTool,
  SolanaDeployTokenTool,
  SolanaDeployCollectionTool,
  SolanaMintNFTTool,
  SolanaTradeTool,
  SolanaRequestFundsTool,
  SolanaRegisterDomainTool,
  SolanaGetWalletAddressTool,
  SolanaPumpfunTokenLaunchTool,
  SolanaCreateImageTool,
  SolanaLendAssetTool,
  SolanaLuloLendTool,
  SolanaLuloWithdrawTool,
  SolanaTPSCalculatorTool,
  SolanaStakeTool,
  SolanaRestakeTool,
  SolanaFetchPriceTool,
  SolanaGetDomainTool,
  SolanaTokenDataTool,
  SolanaTokenDataByTickerTool,
  SolanaCompressedAirdropTool,
  SolanaRaydiumCreateAmmV4,
  SolanaRaydiumCreateClmm,
  SolanaRaydiumCreateCpmm,
  SolanaOpenbookCreateMarket,
  SolanaManifestCreateMarket,
  SolanaLimitOrderTool,
  SolanaBatchOrderTool,
  SolanaCancelAllOrdersTool,
  SolanaWithdrawAllTool,
  SolanaClosePosition,
  SolanaOrcaCreateCLMM,
  SolanaOrcaCreateSingleSideLiquidityPool,
  SolanaOrcaFetchPositions,
  SolanaOrcaOpenCenteredPosition,
  SolanaOrcaOpenSingleSidedPosition,
  SolanaPythFetchPrice,
  SolanaResolveDomainTool,
  SolanaGetOwnedDomains,
  SolanaGetOwnedTldDomains,
  SolanaGetAllTlds,
  SolanaGetMainDomain,
  SolanaResolveAllDomainsTool,
  SolanaCreateGibworkTask,
  SolanaRockPaperScissorsTool,
  SolanaTipLinkTool,
  SolanaListNFTForSaleTool,
  SolanaCancelNFTListingTool,
  SolanaCloseEmptyTokenAccounts,
  SolanaFetchTokenReportSummaryTool,
  SolanaFetchTokenDetailedReportTool,
  Solana3LandCreateSingle,
  Solana3LandCreateCollection,
  SolanaPerpOpenTradeTool,
  SolanaPerpCloseTradeTool,
  SolanaFlashOpenTrade,
  SolanaFlashCloseTrade,
  SolanaCreate2by2Multisig,
  SolanaDepositTo2by2Multisig,
  SolanaTransferFrom2by2Multisig,
  SolanaCreateProposal2by2Multisig,
  SolanaApproveProposal2by2Multisig,
  SolanaExecuteProposal2by2Multisig,
  SolanaRejectProposal2by2Multisig,
  SolanaMeteoraCreateDynamicPool,
  SolanaMeteoraCreateDlmmPool,
  SolanaSendTransactionWithPriorityFee,
  SolanaHeliusWebhookTool,
  SolanaGetHeliusWebhookTool,
  SolanaDeleteHeliusWebhookTool,
  SolanaParseTransactionHeliusTool,
  SolanaGetAllAssetsByOwner,
  SolanaCheckDriftAccountTool,
  SolanaCreateDriftUserAccountTool,
  SolanaCreateDriftVaultTool,
  SolanaDepositIntoDriftVaultTool,
  SolanaDepositToDriftUserAccountTool,
  SolanaDeriveVaultAddressTool,
  SolanaDriftUserAccountInfoTool,
  SolanaDriftVaultInfoTool,
  SolanaRequestDriftWithdrawalTool,
  SolanaTradeDelegatedDriftVaultTool,
  SolanaTradeDriftPerpAccountTool,
  SolanaUpdateDriftVaultDelegateTool,
  SolanaUpdateDriftVaultTool,
  SolanaWithdrawFromDriftAccountTool,
  SolanaWithdrawFromDriftVaultTool,
  SolanaDriftLendAndBorrowAPYTool,
  SolanaDriftEntryQuoteOfPerpTradeTool,
  SolanaDriftPerpMarketFundingRateTool,
  SolanaDriftSpotTokenSwapTool,
  SolanaRequestUnstakeFromDriftInsuranceFundTool,
  SolanaStakeToDriftInsuranceFundTool,
  SolanaUnstakeFromDriftInsuranceFundTool,
  SolanaVoltrGetPositionValues,
  SolanaVoltrDepositStrategy,
  SolanaVoltrWithdrawStrategy,
  SolanaGetAssetTool,
  SolanaGetAssetsByAuthorityTool,
  SolanaGetAssetsByCreatorTool,
  SolanaGetInfoTool,
  SolanaCrossChainSwapTool,
  SolanaAlloraGetPriceInference,
  SolanaAlloraGetAllTopics,
  SolanaAlloraGetInferenceByTopicId,
  SolanaCloseAccountsTool,
  SolanaBurnTokensTool,
  SolanaMergeTokensTool,
  SolanaSpreadTokenTool,
  SolanaSwitchboardSimulateFeed,
  ElfaPingTool,
  ElfaApiKeyStatusTool,
  ElfaGetMentionsTool,
  ElfaTrendingTokensTool,
  ElfaSearchMentionsTool,
  ElfaGetTopMentionsTool,
  ElfaAccountSmartStatsTool,
  SolanaFluxbeamCreatePoolTool,
} from "./index";

export function createSolanaTools(agent: SolanaAgentKit, isServerSide: boolean = false) {
  return [
    new SolanaGetInfoTool(agent),
    new SolanaBalanceTool(agent),
    new SolanaBalanceOtherTool(agent),
    new SolanaTransferTool(agent),
    new SolanaDeployTokenTool(agent),
    new SolanaDeployCollectionTool(agent),
    new SolanaMintNFTTool(agent),
    new SolanaTradeTool(agent),
    new SolanaRequestFundsTool(agent),
    new SolanaRegisterDomainTool(agent),
    new SolanaGetWalletAddressTool(agent),
    new SolanaPumpfunTokenLaunchTool(agent),
    new SolanaCreateImageTool(agent),
    new SolanaLendAssetTool(agent),
    new SolanaLuloLendTool(agent),
    new SolanaLuloWithdrawTool(agent),
    new SolanaTPSCalculatorTool(agent),
    new SolanaStakeTool(agent),
    new SolanaRestakeTool(agent),
    new SolanaFetchPriceTool(agent),
    new SolanaGetDomainTool(agent),
    new SolanaTokenDataTool(agent),
    new SolanaTokenDataByTickerTool(agent),
    new SolanaCompressedAirdropTool(agent),
    new SolanaRaydiumCreateAmmV4(agent),
    new SolanaRaydiumCreateClmm(agent),
    new SolanaRaydiumCreateCpmm(agent),
    new SolanaOpenbookCreateMarket(agent),
    new SolanaManifestCreateMarket(agent),
    new SolanaLimitOrderTool(agent),
    new SolanaBatchOrderTool(agent),
    new SolanaCancelAllOrdersTool(agent),
    new SolanaWithdrawAllTool(agent),
    new SolanaMeteoraCreateDynamicPool(agent),
    new SolanaMeteoraCreateDlmmPool(agent),
    new SolanaClosePosition(agent),
    new SolanaOrcaCreateCLMM(agent),
    new SolanaOrcaCreateSingleSideLiquidityPool(agent),
    new SolanaOrcaFetchPositions(agent),
    new SolanaOrcaOpenCenteredPosition(agent),
    new SolanaOrcaOpenSingleSidedPosition(agent),
    new SolanaPythFetchPrice(agent),
    new SolanaResolveDomainTool(agent),
    new SolanaGetOwnedDomains(agent),
    new SolanaGetOwnedTldDomains(agent),
    new SolanaGetAllTlds(agent),
    new SolanaGetMainDomain(agent),
    new SolanaResolveAllDomainsTool(agent),
    new SolanaCreateGibworkTask(agent),
    new SolanaRockPaperScissorsTool(agent),
    new SolanaTipLinkTool(agent),
    new SolanaListNFTForSaleTool(agent),
    new SolanaCancelNFTListingTool(agent),
    new SolanaCloseEmptyTokenAccounts(agent),
    new SolanaFetchTokenReportSummaryTool(agent),
    new SolanaFetchTokenDetailedReportTool(agent),
    new Solana3LandCreateSingle(agent),
    new Solana3LandCreateCollection(agent),
    new SolanaPerpOpenTradeTool(agent),
    new SolanaPerpCloseTradeTool(agent),
    new SolanaFlashOpenTrade(agent),
    new SolanaFlashCloseTrade(agent),
    new SolanaCreate2by2Multisig(agent),
    new SolanaCreateProposal2by2Multisig(agent),
    new SolanaApproveProposal2by2Multisig(agent),
    new SolanaRejectProposal2by2Multisig(agent),
    new SolanaExecuteProposal2by2Multisig(agent),
    new SolanaDepositTo2by2Multisig(agent),
    new SolanaTransferFrom2by2Multisig(agent),
    new SolanaSendTransactionWithPriorityFee(agent),
    new SolanaHeliusWebhookTool(agent),
    new SolanaGetHeliusWebhookTool(agent),
    new SolanaDeleteHeliusWebhookTool(agent),
    new SolanaParseTransactionHeliusTool(agent),
    new SolanaGetAllAssetsByOwner(agent),
    new SolanaCreateDriftUserAccountTool(agent),
    new SolanaCreateDriftVaultTool(agent),
    new SolanaDepositIntoDriftVaultTool(agent),
    new SolanaDepositToDriftUserAccountTool(agent),
    new SolanaDeriveVaultAddressTool(agent),
    new SolanaCheckDriftAccountTool(agent),
    new SolanaDriftUserAccountInfoTool(agent),
    new SolanaRequestDriftWithdrawalTool(agent),
    new SolanaTradeDelegatedDriftVaultTool(agent),
    new SolanaTradeDriftPerpAccountTool(agent),
    new SolanaUpdateDriftVaultDelegateTool(agent),
    new SolanaUpdateDriftVaultTool(agent),
    new SolanaDriftVaultInfoTool(agent),
    new SolanaWithdrawFromDriftAccountTool(agent),
    new SolanaWithdrawFromDriftVaultTool(agent),
    new SolanaDriftSpotTokenSwapTool(agent),
    new SolanaStakeToDriftInsuranceFundTool(agent),
    new SolanaRequestUnstakeFromDriftInsuranceFundTool(agent),
    new SolanaUnstakeFromDriftInsuranceFundTool(agent),
    new SolanaDriftLendAndBorrowAPYTool(agent),
    new SolanaDriftEntryQuoteOfPerpTradeTool(agent),
    new SolanaDriftPerpMarketFundingRateTool(agent),
    new SolanaVoltrGetPositionValues(agent),
    new SolanaVoltrDepositStrategy(agent),
    new SolanaVoltrWithdrawStrategy(agent),
    new SolanaGetAssetTool(agent),
    new SolanaGetAssetsByAuthorityTool(agent),
    new SolanaGetAssetsByCreatorTool(agent),
    new SolanaSwitchboardSimulateFeed(agent),
    new SolanaCrossChainSwapTool(agent),
    new SolanaAlloraGetAllTopics(agent),
    new SolanaAlloraGetInferenceByTopicId(agent),
    new SolanaCloseAccountsTool(agent),
    new SolanaBurnTokensTool(agent),
    new SolanaMergeTokensTool(agent),
    new SolanaSpreadTokenTool(agent),
    new SolanaAlloraGetPriceInference(agent),
    new ElfaPingTool(agent),
    new ElfaApiKeyStatusTool(agent),
    new ElfaGetMentionsTool(agent),
    new ElfaTrendingTokensTool(agent),
    new ElfaSearchMentionsTool(agent),
    new ElfaGetTopMentionsTool(agent),
    new ElfaAccountSmartStatsTool(agent),
    new SolanaFluxbeamCreatePoolTool(agent),
  ];
}
